const data = [
    {
        "restaurant": {
            "R": {
                "res_id": 18710176
            },
            "apikey": "05d2f9480e0347e4c0e0ea6095c55a14",
            "id": "18710176",
            "name": "The Garden",
            "url": "https://www.zomato.com/jakarta/the-garden-pantai-indah-kapuk?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
            "location": {
                "address": "Ruko Garden House, Blok B No. 27, Jl. Pantai Indah Kapuk, Pantai Indah Kapuk, Jakarta",
                "locality": "Ruko Garden House, Pantai Indah Kapuk",
                "city": "Jakarta",
                "city_id": 74,
                "latitude": "-6.1103195230",
                "longitude": "106.7378563061",
                "zipcode": "",
                "country_id": 94,
                "locality_verbose": "Ruko Garden House, Pantai Indah Kapuk, Jakarta"
            },
            "switch_to_order_menu": 0,
            "cuisines": "Western, Asian",
            "average_cost_for_two": 250000,
            "price_range": 3,
            "currency": "IDR",
            "offers": [],
            "opentable_support": 0,
            "is_zomato_book_res": 0,
            "mezzo_provider": "OTHER",
            "is_book_form_web_view": 0,
            "book_form_web_view_url": "",
            "book_again_url": "",
            "thumb": "https://b.zmtcdn.com/data/reviews_photos/1b0/1e87a4806e59ad67fceabbfe3b6ab1b0_1547996783.jpg?fit=around%7C200%3A200&crop=200%3A200%3B%2A%2C%2A",
            "user_rating": {
                "aggregate_rating": "4.5",
                "rating_text": "Excellent",
                "rating_color": "3F7E00",
                "votes": "990",
                "has_fake_reviews": 0
            },
            "photos_url": "https://www.zomato.com/jakarta/the-garden-pantai-indah-kapuk/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop",
            "menu_url": "https://www.zomato.com/jakarta/the-garden-pantai-indah-kapuk/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop",
            "featured_image": "https://b.zmtcdn.com/data/reviews_photos/1b0/1e87a4806e59ad67fceabbfe3b6ab1b0_1547996783.jpg?output-format=webp",
            "has_online_delivery": 0,
            "is_delivering_now": 0,
            "has_fake_reviews": 0,
            "include_bogo_offers": true,
            "deeplink": "zomato://restaurant/18710176",
            "is_table_reservation_supported": 0,
            "has_table_booking": 0,
            "events_url": "https://www.zomato.com/jakarta/the-garden-pantai-indah-kapuk/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1"
        }
    },
    {
        "restaurant": {
            "R": {
                "res_id": 7407943
            },
            "apikey": "05d2f9480e0347e4c0e0ea6095c55a14",
            "id": "7407943",
            "name": "Sushi Tei",
            "url": "https://www.zomato.com/jakarta/sushi-tei-kelapa-gading?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
            "location": {
                "address": "Mall Kelapa Gading 5, Lantai 3, Jl. Kelapa Gading Boulevard, Kelapa Gading, Jakarta",
                "locality": "Mall Kelapa Gading, Kelapa Gading",
                "city": "Jakarta",
                "city_id": 74,
                "latitude": "-6.1567477991",
                "longitude": "106.9103562087",
                "zipcode": "",
                "country_id": 94,
                "locality_verbose": "Mall Kelapa Gading, Kelapa Gading, Jakarta"
            },
            "switch_to_order_menu": 0,
            "cuisines": "Sushi, Ramen, Japanese",
            "average_cost_for_two": 280000,
            "price_range": 3,
            "currency": "IDR",
            "offers": [],
            "opentable_support": 0,
            "is_zomato_book_res": 0,
            "mezzo_provider": "OTHER",
            "is_book_form_web_view": 0,
            "book_form_web_view_url": "",
            "book_again_url": "",
            "thumb": "https://b.zmtcdn.com/data/pictures/chains/3/7400843/b91a8162708aac39647d6b59732361a6.jpg?fit=around%7C200%3A200&crop=200%3A200%3B%2A%2C%2A",
            "user_rating": {
                "aggregate_rating": "4.4",
                "rating_text": "Very Good",
                "rating_color": "5BA829",
                "votes": "677",
                "has_fake_reviews": 0
            },
            "photos_url": "https://www.zomato.com/jakarta/sushi-tei-kelapa-gading/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop",
            "menu_url": "https://www.zomato.com/jakarta/sushi-tei-kelapa-gading/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop",
            "featured_image": "https://b.zmtcdn.com/data/pictures/chains/3/7400843/b91a8162708aac39647d6b59732361a6.jpg",
            "has_online_delivery": 0,
            "is_delivering_now": 0,
            "has_fake_reviews": 0,
            "include_bogo_offers": true,
            "deeplink": "zomato://restaurant/7407943",
            "is_table_reservation_supported": 0,
            "has_table_booking": 0,
            "events_url": "https://www.zomato.com/jakarta/sushi-tei-kelapa-gading/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1"
        }
    },
    {
        "restaurant": {
            "R": {
                "res_id": 18366214
            },
            "apikey": "05d2f9480e0347e4c0e0ea6095c55a14",
            "id": "18366214",
            "name": "Wing Heng Hongkong Dim Sum Shop",
            "url": "https://www.zomato.com/jakarta/wing-heng-hongkong-dim-sum-shop-pluit?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
            "location": {
                "address": "Jl. Pluit Karang Utara, Blok A4U No. 65A, Pluit, Jakarta",
                "locality": "Pluit",
                "city": "Jakarta",
                "city_id": 74,
                "latitude": "-6.1127701302",
                "longitude": "106.7808256298",
                "zipcode": "",
                "country_id": 94,
                "locality_verbose": "Pluit, Jakarta"
            },
            "switch_to_order_menu": 0,
            "cuisines": "Dimsum, Chinese",
            "average_cost_for_two": 150000,
            "price_range": 3,
            "currency": "IDR",
            "offers": [],
            "opentable_support": 0,
            "is_zomato_book_res": 0,
            "mezzo_provider": "OTHER",
            "is_book_form_web_view": 0,
            "book_form_web_view_url": "",
            "book_again_url": "",
            "thumb": "https://b.zmtcdn.com/data/reviews_photos/19e/c13447c5e01f69021b4d53829c5b619e_1530292565.jpg?fit=around%7C200%3A200&crop=200%3A200%3B%2A%2C%2A",
            "user_rating": {
                "aggregate_rating": "4.6",
                "rating_text": "Excellent",
                "rating_color": "3F7E00",
                "votes": "857",
                "has_fake_reviews": 0
            },
            "photos_url": "https://www.zomato.com/jakarta/wing-heng-hongkong-dim-sum-shop-pluit/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop",
            "menu_url": "https://www.zomato.com/jakarta/wing-heng-hongkong-dim-sum-shop-pluit/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop",
            "featured_image": "https://b.zmtcdn.com/data/reviews_photos/19e/c13447c5e01f69021b4d53829c5b619e_1530292565.jpg",
            "has_online_delivery": 0,
            "is_delivering_now": 0,
            "has_fake_reviews": 0,
            "include_bogo_offers": true,
            "deeplink": "zomato://restaurant/18366214",
            "is_table_reservation_supported": 0,
            "has_table_booking": 0,
            "events_url": "https://www.zomato.com/jakarta/wing-heng-hongkong-dim-sum-shop-pluit/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1"
        }
    },
    {
        "restaurant": {
            "R": {
                "res_id": 7418799
            },
            "apikey": "05d2f9480e0347e4c0e0ea6095c55a14",
            "id": "7418799",
            "name": "KOI Cafe",
            "url": "https://www.zomato.com/jakarta/koi-cafe-penjaringan?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
            "location": {
                "address": "Emporium Pluit Mall, Lantai 3, Jl. Pluit Selatan Raya, Penjaringan, Jakarta",
                "locality": "Emporium Pluit Mall, Penjaringan",
                "city": "Jakarta",
                "city_id": 74,
                "latitude": "-6.1275905471",
                "longitude": "106.7906093225",
                "zipcode": "",
                "country_id": 94,
                "locality_verbose": "Emporium Pluit Mall, Penjaringan, Jakarta"
            },
            "switch_to_order_menu": 0,
            "cuisines": "Bubble Tea, Beverages",
            "average_cost_for_two": 60000,
            "price_range": 1,
            "currency": "IDR",
            "offers": [],
            "opentable_support": 0,
            "is_zomato_book_res": 0,
            "mezzo_provider": "OTHER",
            "is_book_form_web_view": 0,
            "book_form_web_view_url": "",
            "book_again_url": "",
            "thumb": "https://b.zmtcdn.com/data/pictures/9/7418799/d0b0bef24ae65b466c71e8fa014f57c0.jpg?fit=around%7C200%3A200&crop=200%3A200%3B%2A%2C%2A",
            "user_rating": {
                "aggregate_rating": "4.2",
                "rating_text": "Very Good",
                "rating_color": "5BA829",
                "votes": "142",
                "has_fake_reviews": 0
            },
            "photos_url": "https://www.zomato.com/jakarta/koi-cafe-penjaringan/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop",
            "menu_url": "https://www.zomato.com/jakarta/koi-cafe-penjaringan/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop",
            "featured_image": "https://b.zmtcdn.com/data/pictures/9/7418799/d0b0bef24ae65b466c71e8fa014f57c0.jpg",
            "has_online_delivery": 0,
            "is_delivering_now": 0,
            "has_fake_reviews": 0,
            "include_bogo_offers": true,
            "deeplink": "zomato://restaurant/7418799",
            "is_table_reservation_supported": 0,
            "has_table_booking": 0,
            "events_url": "https://www.zomato.com/jakarta/koi-cafe-penjaringan/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1"
        }
    },
    {
        "restaurant": {
            "R": {
                "res_id": 18899024
            },
            "apikey": "05d2f9480e0347e4c0e0ea6095c55a14",
            "id": "18899024",
            "name": "Shu Guo Yin Xiang",
            "url": "https://www.zomato.com/jakarta/shu-guo-yin-xiang-pantai-indah-kapuk?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
            "location": {
                "address": "Ruko Crown Golf, Blok D No. 62-63, Bukit Golf Mediterania, Jl. Marina Indah Raya, Pantai Indah Kapuk, Jakarta",
                "locality": "Ruko Crown Golf, Pantai Indah Kapuk",
                "city": "Jakarta",
                "city_id": 74,
                "latitude": "-6.1108050000",
                "longitude": "106.7388230000",
                "zipcode": "",
                "country_id": 94,
                "locality_verbose": "Ruko Crown Golf, Pantai Indah Kapuk, Jakarta"
            },
            "switch_to_order_menu": 0,
            "cuisines": "Chinese",
            "average_cost_for_two": 250000,
            "price_range": 3,
            "currency": "IDR",
            "offers": [],
            "opentable_support": 0,
            "is_zomato_book_res": 0,
            "mezzo_provider": "OTHER",
            "is_book_form_web_view": 0,
            "book_form_web_view_url": "",
            "book_again_url": "",
            "thumb": "",
            "user_rating": {
                "aggregate_rating": "4.0",
                "rating_text": "Very Good",
                "rating_color": "5BA829",
                "votes": "58",
                "has_fake_reviews": 0
            },
            "photos_url": "https://www.zomato.com/jakarta/shu-guo-yin-xiang-pantai-indah-kapuk/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop",
            "menu_url": "https://www.zomato.com/jakarta/shu-guo-yin-xiang-pantai-indah-kapuk/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop",
            "featured_image": "",
            "has_online_delivery": 0,
            "is_delivering_now": 0,
            "has_fake_reviews": 0,
            "include_bogo_offers": true,
            "deeplink": "zomato://restaurant/18899024",
            "is_table_reservation_supported": 0,
            "has_table_booking": 0,
            "events_url": "https://www.zomato.com/jakarta/shu-guo-yin-xiang-pantai-indah-kapuk/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1"
        }
    },
    {
        "restaurant": {
            "R": {
                "res_id": 18600243
            },
            "apikey": "05d2f9480e0347e4c0e0ea6095c55a14",
            "id": "18600243",
            "name": "Onokabe",
            "url": "https://www.zomato.com/jakarta/onokabe-pluit?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
            "location": {
                "address": "Pluit Junction, Lantai Ground, Jl. Pluit Selatan Raya, Pluit, Jakarta",
                "locality": "Pluit Junction Mall, Pluit",
                "city": "Jakarta",
                "city_id": 74,
                "latitude": "-6.1268094827",
                "longitude": "106.7912942916",
                "zipcode": "",
                "country_id": 94,
                "locality_verbose": "Pluit Junction Mall, Pluit, Jakarta"
            },
            "switch_to_order_menu": 0,
            "cuisines": "Japanese",
            "average_cost_for_two": 300000,
            "price_range": 3,
            "currency": "IDR",
            "offers": [],
            "opentable_support": 0,
            "is_zomato_book_res": 0,
            "mezzo_provider": "OTHER",
            "is_book_form_web_view": 0,
            "book_form_web_view_url": "",
            "book_again_url": "",
            "thumb": "https://b.zmtcdn.com/data/pictures/chains/6/18386856/c5ac881c5c55d33dddf59e960489777c.jpg?fit=around%7C200%3A200&crop=200%3A200%3B%2A%2C%2A",
            "user_rating": {
                "aggregate_rating": "3.9",
                "rating_text": "Good",
                "rating_color": "9ACD32",
                "votes": "492",
                "has_fake_reviews": 0
            },
            "photos_url": "https://www.zomato.com/jakarta/onokabe-pluit/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop",
            "menu_url": "https://www.zomato.com/jakarta/onokabe-pluit/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop",
            "featured_image": "http://b.zmtcdn.com/data/pictures/chains/6/18386856/c5ac881c5c55d33dddf59e960489777c.jpg",
            "has_online_delivery": 0,
            "is_delivering_now": 0,
            "has_fake_reviews": 0,
            "include_bogo_offers": true,
            "deeplink": "zomato://restaurant/18600243",
            "is_table_reservation_supported": 0,
            "has_table_booking": 0,
            "events_url": "https://www.zomato.com/jakarta/onokabe-pluit/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1"
        }
    },
    {
        "restaurant": {
            "R": {
                "res_id": 7413472
            },
            "apikey": "05d2f9480e0347e4c0e0ea6095c55a14",
            "id": "7413472",
            "name": "Bandar Djakarta",
            "url": "https://www.zomato.com/jakarta/bandar-djakarta-ancol?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
            "location": {
                "address": "Taman Impian Jaya Ancol, Jl. Lodan Timur, Ancol, Jakarta 14430",
                "locality": "Taman Impian Jaya Ancol, Ancol",
                "city": "Jakarta",
                "city_id": 74,
                "latitude": "-6.1225627791",
                "longitude": "106.8437606469",
                "zipcode": "14430",
                "country_id": 94,
                "locality_verbose": "Taman Impian Jaya Ancol, Ancol, Jakarta"
            },
            "switch_to_order_menu": 0,
            "cuisines": "Seafood",
            "average_cost_for_two": 250000,
            "price_range": 3,
            "currency": "IDR",
            "offers": [],
            "opentable_support": 0,
            "is_zomato_book_res": 0,
            "mezzo_provider": "OTHER",
            "is_book_form_web_view": 0,
            "book_form_web_view_url": "",
            "book_again_url": "",
            "thumb": "https://b.zmtcdn.com/data/pictures/chains/4/7411044/3d284493e33d66ffc0b4f7deea109930.jpg?fit=around%7C200%3A200&crop=200%3A200%3B%2A%2C%2A",
            "user_rating": {
                "aggregate_rating": "4.6",
                "rating_text": "Excellent",
                "rating_color": "3F7E00",
                "votes": "1539",
                "has_fake_reviews": 0
            },
            "photos_url": "https://www.zomato.com/jakarta/bandar-djakarta-ancol/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop",
            "menu_url": "https://www.zomato.com/jakarta/bandar-djakarta-ancol/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop",
            "featured_image": "https://b.zmtcdn.com/data/pictures/chains/4/7411044/3d284493e33d66ffc0b4f7deea109930.jpg?output-format=webp",
            "has_online_delivery": 0,
            "is_delivering_now": 0,
            "has_fake_reviews": 0,
            "include_bogo_offers": true,
            "deeplink": "zomato://restaurant/7413472",
            "is_table_reservation_supported": 0,
            "has_table_booking": 0,
            "events_url": "https://www.zomato.com/jakarta/bandar-djakarta-ancol/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1"
        }
    },
    {
        "restaurant": {
            "R": {
                "res_id": 18335207
            },
            "apikey": "05d2f9480e0347e4c0e0ea6095c55a14",
            "id": "18335207",
            "name": "Sushi Hiro",
            "url": "https://www.zomato.com/jakarta/sushi-hiro-pantai-indah-kapuk?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
            "location": {
                "address": "Ruko Garden House, Blok B No. 18D, Bukit Golf Mediterania, Jl. Raya Pantai Indah Kapuk, Pantai Indah Kapuk, Jakarta",
                "locality": "Ruko Garden House, Pantai Indah Kapuk",
                "city": "Jakarta",
                "city_id": 74,
                "latitude": "-6.1107932435",
                "longitude": "106.7375217006",
                "zipcode": "",
                "country_id": 94,
                "locality_verbose": "Ruko Garden House, Pantai Indah Kapuk, Jakarta"
            },
            "switch_to_order_menu": 0,
            "cuisines": "Sushi, Japanese",
            "average_cost_for_two": 400000,
            "price_range": 4,
            "currency": "IDR",
            "offers": [],
            "opentable_support": 0,
            "is_zomato_book_res": 0,
            "mezzo_provider": "OTHER",
            "is_book_form_web_view": 0,
            "book_form_web_view_url": "",
            "book_again_url": "",
            "thumb": "https://b.zmtcdn.com/data/pictures/3/18567253/234c8d74022f82e43556504198cbb885.jpg?fit=around%7C200%3A200&crop=200%3A200%3B%2A%2C%2A",
            "user_rating": {
                "aggregate_rating": "4.7",
                "rating_text": "Excellent",
                "rating_color": "3F7E00",
                "votes": "1774",
                "has_fake_reviews": 0
            },
            "photos_url": "https://www.zomato.com/jakarta/sushi-hiro-pantai-indah-kapuk/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop",
            "menu_url": "https://www.zomato.com/jakarta/sushi-hiro-pantai-indah-kapuk/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop",
            "featured_image": "https://b.zmtcdn.com/data/pictures/3/18567253/234c8d74022f82e43556504198cbb885.jpg",
            "has_online_delivery": 0,
            "is_delivering_now": 0,
            "has_fake_reviews": 0,
            "include_bogo_offers": true,
            "deeplink": "zomato://restaurant/18335207",
            "is_table_reservation_supported": 0,
            "has_table_booking": 0,
            "events_url": "https://www.zomato.com/jakarta/sushi-hiro-pantai-indah-kapuk/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1"
        }
    },
    {
        "restaurant": {
            "R": {
                "res_id": 18941833
            },
            "apikey": "05d2f9480e0347e4c0e0ea6095c55a14",
            "id": "18941833",
            "name": "Sushi Hiro",
            "url": "https://www.zomato.com/jakarta/sushi-hiro-pluit?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
            "location": {
                "address": "Jl. Pluit Putra Raya No. 12A, Pluit, Jakarta",
                "locality": "Pluit",
                "city": "Jakarta",
                "city_id": 74,
                "latitude": "-6.1212293226",
                "longitude": "106.7916456610",
                "zipcode": "",
                "country_id": 94,
                "locality_verbose": "Pluit, Jakarta"
            },
            "switch_to_order_menu": 0,
            "cuisines": "Sushi, Japanese",
            "average_cost_for_two": 400000,
            "price_range": 4,
            "currency": "IDR",
            "offers": [],
            "opentable_support": 0,
            "is_zomato_book_res": 0,
            "mezzo_provider": "OTHER",
            "is_book_form_web_view": 0,
            "book_form_web_view_url": "",
            "book_again_url": "",
            "thumb": "https://b.zmtcdn.com/data/pictures/3/18567253/234c8d74022f82e43556504198cbb885.jpg?fit=around%7C200%3A200&crop=200%3A200%3B%2A%2C%2A",
            "user_rating": {
                "aggregate_rating": "4.6",
                "rating_text": "Excellent",
                "rating_color": "3F7E00",
                "votes": "471",
                "has_fake_reviews": 0
            },
            "photos_url": "https://www.zomato.com/jakarta/sushi-hiro-pluit/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop",
            "menu_url": "https://www.zomato.com/jakarta/sushi-hiro-pluit/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop",
            "featured_image": "https://b.zmtcdn.com/data/pictures/3/18567253/234c8d74022f82e43556504198cbb885.jpg",
            "has_online_delivery": 0,
            "is_delivering_now": 0,
            "has_fake_reviews": 0,
            "include_bogo_offers": true,
            "deeplink": "zomato://restaurant/18941833",
            "is_table_reservation_supported": 0,
            "has_table_booking": 0,
            "events_url": "https://www.zomato.com/jakarta/sushi-hiro-pluit/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1"
        }
    },
    {
        "restaurant": {
            "R": {
                "res_id": 18997929
            },
            "apikey": "05d2f9480e0347e4c0e0ea6095c55a14",
            "id": "18997929",
            "name": "Eighteen Pies",
            "url": "https://www.zomato.com/jakarta/eighteen-pies-pantai-indah-kapuk?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
            "location": {
                "address": "Ruko Crown Golf, Blok D No. 16, Bukit Golf Mediterania, Jl. Marina Indah Raya, Pantai Indah Kapuk, Jakarta",
                "locality": "Ruko Crown Golf, Pantai Indah Kapuk",
                "city": "Jakarta",
                "city_id": 74,
                "latitude": "-6.1120080000",
                "longitude": "106.7379560000",
                "zipcode": "",
                "country_id": 94,
                "locality_verbose": "Ruko Crown Golf, Pantai Indah Kapuk, Jakarta"
            },
            "switch_to_order_menu": 0,
            "cuisines": "Asian, Western, Coffee, Bakery",
            "average_cost_for_two": 250000,
            "price_range": 3,
            "currency": "IDR",
            "offers": [],
            "opentable_support": 0,
            "is_zomato_book_res": 0,
            "mezzo_provider": "OTHER",
            "is_book_form_web_view": 0,
            "book_form_web_view_url": "",
            "book_again_url": "",
            "thumb": "https://b.zmtcdn.com/data/reviews_photos/791/e041f6a1fd3c88cf98b0271dc1088791_1553880428.jpg?fit=around%7C200%3A200&crop=200%3A200%3B%2A%2C%2A",
            "user_rating": {
                "aggregate_rating": "3.8",
                "rating_text": "Good",
                "rating_color": "9ACD32",
                "votes": "30",
                "custom_rating_text": "NEW",
                "custom_rating_text_background": "#89959B",
                "rating_tool_tip": "This restaurant is newly opened. The rating will appear once the restaurant completes 60 days in operation.",
                "has_fake_reviews": 0
            },
            "photos_url": "https://www.zomato.com/jakarta/eighteen-pies-pantai-indah-kapuk/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop",
            "menu_url": "https://www.zomato.com/jakarta/eighteen-pies-pantai-indah-kapuk/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop",
            "featured_image": "http://b.zmtcdn.com/data/reviews_photos/791/e041f6a1fd3c88cf98b0271dc1088791_1553880428.jpg",
            "has_online_delivery": 0,
            "is_delivering_now": 0,
            "has_fake_reviews": 0,
            "include_bogo_offers": true,
            "deeplink": "zomato://restaurant/18997929",
            "is_table_reservation_supported": 0,
            "has_table_booking": 0,
            "events_url": "https://www.zomato.com/jakarta/eighteen-pies-pantai-indah-kapuk/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1"
        }
    }
]

module.exports = data