const data = {
    "popularity": "5.00",
    "nightlife_index": "4.94",
    "nearby_res": [
        "18560991",
        "18868971",
        "18460102",
        "7402207",
        "7404202",
        "7403192",
        "7403433",
        "7419364",
        "18570658"
    ],
    "top_cuisines": [
        "Western",
        "Indonesian",
        "Coffee",
        "Cafe",
        "Asian"
    ],
    "popularity_res": "100",
    "nightlife_res": "10",
    "subzone": "Kemang",
    "subzone_id": 72939,
    "city": "Jakarta",
    "location": {
        "entity_type": "zone",
        "entity_id": 74004,
        "title": "South Jakarta, Jakarta",
        "latitude": -6.262606,
        "longitude": 106.818039,
        "city_id": 74,
        "city_name": "Jakarta",
        "country_id": 94,
        "country_name": "Indonesia"
    },
    "num_restaurant": 5916,
    "best_rated_restaurant": [
        {
            "restaurant": {
                "R": {
                    "res_id": 18819628
                },
                "apikey": "05d2f9480e0347e4c0e0ea6095c55a14",
                "id": "18819628",
                "name": "Cork & Screw Country Club",
                "url": "https://www.zomato.com/jakarta/cork-screw-country-club-senayan?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
                "location": {
                    "address": "Senayan National Golf Club - The Maj Senayan, Jl. Asia Afrika Pintu IX, Senayan, Jakarta",
                    "locality": "Senayan National Golf Club, Senayan",
                    "city": "Jakarta",
                    "city_id": 74,
                    "latitude": "-6.2243819238",
                    "longitude": "106.7969353795",
                    "zipcode": "",
                    "country_id": 94,
                    "locality_verbose": "Senayan National Golf Club, Senayan, Jakarta"
                },
                "switch_to_order_menu": 0,
                "cuisines": "European, Grill, Asian",
                "average_cost_for_two": 750000,
                "price_range": 4,
                "currency": "IDR",
                "offers": [],
                "opentable_support": 0,
                "is_zomato_book_res": 0,
                "mezzo_provider": "OTHER",
                "is_book_form_web_view": 0,
                "book_form_web_view_url": "",
                "book_again_url": "",
                "thumb": "https://b.zmtcdn.com/data/reviews_photos/583/189bbde29df54b118c84ddf10f1cf583_1551765021.jpg?fit=around%7C200%3A200&crop=200%3A200%3B%2A%2C%2A",
                "user_rating": {
                    "aggregate_rating": "4.2",
                    "rating_text": "Very Good",
                    "rating_color": "5BA829",
                    "votes": "271",
                    "has_fake_reviews": 0
                },
                "photos_url": "https://www.zomato.com/jakarta/cork-screw-country-club-senayan/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop",
                "menu_url": "https://www.zomato.com/jakarta/cork-screw-country-club-senayan/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop",
                "featured_image": "https://b.zmtcdn.com/data/reviews_photos/583/189bbde29df54b118c84ddf10f1cf583_1551765021.jpg",
                "has_online_delivery": 0,
                "is_delivering_now": 0,
                "has_fake_reviews": 0,
                "include_bogo_offers": true,
                "deeplink": "zomato://restaurant/18819628",
                "is_table_reservation_supported": 0,
                "has_table_booking": 0,
                "events_url": "https://www.zomato.com/jakarta/cork-screw-country-club-senayan/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1"
            }
        },
        {
            "restaurant": {
                "R": {
                    "res_id": 18560991
                },
                "apikey": "05d2f9480e0347e4c0e0ea6095c55a14",
                "id": "18560991",
                "name": "Lawless Burgerbar",
                "url": "https://www.zomato.com/jakarta/lawless-burgerbar-kemang?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
                "location": {
                    "address": "Jl. Kemang Selatan VIII No. 67H-67I, Kemang, Jakarta",
                    "locality": "Kemang",
                    "city": "Jakarta",
                    "city_id": 74,
                    "latitude": "-6.2680024103",
                    "longitude": "106.8141983450",
                    "zipcode": "",
                    "country_id": 94,
                    "locality_verbose": "Kemang, Jakarta"
                },
                "switch_to_order_menu": 0,
                "cuisines": "Burger, Western",
                "average_cost_for_two": 150000,
                "price_range": 3,
                "currency": "IDR",
                "offers": [],
                "opentable_support": 0,
                "is_zomato_book_res": 0,
                "mezzo_provider": "OTHER",
                "is_book_form_web_view": 0,
                "book_form_web_view_url": "",
                "book_again_url": "",
                "thumb": "https://b.zmtcdn.com/data/pictures/chains/1/18560991/4467c4869a3fbb4bc1c16b95c8e82898.jpeg?fit=around%7C200%3A200&crop=200%3A200%3B%2A%2C%2A",
                "user_rating": {
                    "aggregate_rating": "4.7",
                    "rating_text": "Excellent",
                    "rating_color": "3F7E00",
                    "votes": "970",
                    "has_fake_reviews": 0
                },
                "photos_url": "https://www.zomato.com/jakarta/lawless-burgerbar-kemang/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop",
                "menu_url": "https://www.zomato.com/jakarta/lawless-burgerbar-kemang/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop",
                "featured_image": "https://b.zmtcdn.com/data/pictures/chains/1/18560991/4467c4869a3fbb4bc1c16b95c8e82898.jpeg?output-format=webp",
                "has_online_delivery": 0,
                "is_delivering_now": 0,
                "has_fake_reviews": 0,
                "include_bogo_offers": true,
                "deeplink": "zomato://restaurant/18560991",
                "is_table_reservation_supported": 0,
                "has_table_booking": 0,
                "events_url": "https://www.zomato.com/jakarta/lawless-burgerbar-kemang/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1"
            }
        },
        {
            "restaurant": {
                "R": {
                    "res_id": 18338211
                },
                "apikey": "05d2f9480e0347e4c0e0ea6095c55a14",
                "id": "18338211",
                "name": "Yakiniku Kintan Buffet",
                "url": "https://www.zomato.com/jakarta/yakiniku-kintan-buffet-gandaria?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
                "location": {
                    "address": "Gandaria City, Lantai Upper Ground, Jl. Sultan Iskandar Muda, Gandaria, Jakarta",
                    "locality": "Gandaria City Mall, Gandaria",
                    "city": "Jakarta",
                    "city_id": 74,
                    "latitude": "-6.2432213923",
                    "longitude": "106.7837670073",
                    "zipcode": "",
                    "country_id": 94,
                    "locality_verbose": "Gandaria City Mall, Gandaria, Jakarta"
                },
                "switch_to_order_menu": 0,
                "cuisines": "Grill, Japanese",
                "average_cost_for_two": 600000,
                "price_range": 4,
                "currency": "IDR",
                "offers": [],
                "opentable_support": 0,
                "is_zomato_book_res": 0,
                "mezzo_provider": "OTHER",
                "is_book_form_web_view": 0,
                "book_form_web_view_url": "",
                "book_again_url": "",
                "thumb": "https://b.zmtcdn.com/data/pictures/chains/1/18338211/52855a44b1b54e9570facc1b0d3a792a.jpg?fit=around%7C200%3A200&crop=200%3A200%3B%2A%2C%2A",
                "user_rating": {
                    "aggregate_rating": "4.6",
                    "rating_text": "Excellent",
                    "rating_color": "3F7E00",
                    "votes": "1039",
                    "has_fake_reviews": 0
                },
                "photos_url": "https://www.zomato.com/jakarta/yakiniku-kintan-buffet-gandaria/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop",
                "menu_url": "https://www.zomato.com/jakarta/yakiniku-kintan-buffet-gandaria/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop",
                "featured_image": "https://b.zmtcdn.com/data/pictures/chains/1/18338211/52855a44b1b54e9570facc1b0d3a792a.jpg",
                "has_online_delivery": 0,
                "is_delivering_now": 0,
                "has_fake_reviews": 0,
                "include_bogo_offers": true,
                "deeplink": "zomato://restaurant/18338211",
                "is_table_reservation_supported": 0,
                "has_table_booking": 0,
                "events_url": "https://www.zomato.com/jakarta/yakiniku-kintan-buffet-gandaria/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1"
            }
        },
        {
            "restaurant": {
                "R": {
                    "res_id": 7403002
                },
                "apikey": "05d2f9480e0347e4c0e0ea6095c55a14",
                "id": "7403002",
                "name": "Union",
                "url": "https://www.zomato.com/jakarta/union-senayan?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
                "location": {
                    "address": "Plaza Senayan, Lantai Ground, Jl. Asia Afrika, Senayan, Jakarta",
                    "locality": "Plaza Senayan, Senayan",
                    "city": "Jakarta",
                    "city_id": 74,
                    "latitude": "-6.2230737652",
                    "longitude": "106.7984802648",
                    "zipcode": "",
                    "country_id": 94,
                    "locality_verbose": "Plaza Senayan, Senayan, Jakarta"
                },
                "switch_to_order_menu": 0,
                "cuisines": "Italian, American, Desserts",
                "average_cost_for_two": 550000,
                "price_range": 4,
                "currency": "IDR",
                "offers": [],
                "opentable_support": 0,
                "is_zomato_book_res": 0,
                "mezzo_provider": "OTHER",
                "is_book_form_web_view": 0,
                "book_form_web_view_url": "",
                "book_again_url": "",
                "thumb": "https://b.zmtcdn.com/data/reviews_photos/a65/1f69b055699db9c386ebe41573567a65_1495903639.jpg?fit=around%7C200%3A200&crop=200%3A200%3B%2A%2C%2A",
                "user_rating": {
                    "aggregate_rating": "4.7",
                    "rating_text": "Excellent",
                    "rating_color": "3F7E00",
                    "votes": "1961",
                    "has_fake_reviews": 0
                },
                "photos_url": "https://www.zomato.com/jakarta/union-senayan/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop",
                "menu_url": "https://www.zomato.com/jakarta/union-senayan/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop",
                "featured_image": "https://b.zmtcdn.com/data/reviews_photos/a65/1f69b055699db9c386ebe41573567a65_1495903639.jpg",
                "has_online_delivery": 0,
                "is_delivering_now": 0,
                "has_fake_reviews": 0,
                "include_bogo_offers": true,
                "deeplink": "zomato://restaurant/7403002",
                "is_table_reservation_supported": 0,
                "has_table_booking": 0,
                "events_url": "https://www.zomato.com/jakarta/union-senayan/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1"
            }
        },
        {
            "restaurant": {
                "R": {
                    "res_id": 7421967
                },
                "apikey": "05d2f9480e0347e4c0e0ea6095c55a14",
                "id": "7421967",
                "name": "3 Wise Monkeys",
                "url": "https://www.zomato.com/jakarta/3-wise-monkeys-senopati?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
                "location": {
                    "address": "Jl. Suryo No. 26, Senopati, Jakarta",
                    "locality": "Senopati",
                    "city": "Jakarta",
                    "city_id": 74,
                    "latitude": "-6.2355930484",
                    "longitude": "106.8133427203",
                    "zipcode": "",
                    "country_id": 94,
                    "locality_verbose": "Senopati, Jakarta"
                },
                "switch_to_order_menu": 0,
                "cuisines": "Japanese, Sushi",
                "average_cost_for_two": 450000,
                "price_range": 4,
                "currency": "IDR",
                "offers": [],
                "opentable_support": 0,
                "is_zomato_book_res": 1,
                "mezzo_provider": "ZOMATO_BOOK",
                "is_book_form_web_view": 0,
                "book_form_web_view_url": "",
                "thumb": "https://b.zmtcdn.com/data/res_imagery/7421967_RESTAURANT_4ac7c035ff2a9c317c1552a89f456061.jpg?fit=around%7C200%3A200&crop=200%3A200%3B%2A%2C%2A",
                "user_rating": {
                    "aggregate_rating": "4.5",
                    "rating_text": "Terbaik",
                    "rating_color": "3F7E00",
                    "votes": "1641",
                    "has_fake_reviews": 0
                },
                "photos_url": "https://www.zomato.com/jakarta/3-wise-monkeys-senopati/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop",
                "menu_url": "https://www.zomato.com/jakarta/3-wise-monkeys-senopati/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop",
                "featured_image": "https://b.zmtcdn.com/data/res_imagery/7421967_RESTAURANT_4ac7c035ff2a9c317c1552a89f456061.jpg?output-format=webp",
                "medio_provider": "",
                "has_online_delivery": 0,
                "is_delivering_now": 0,
                "has_fake_reviews": 0,
                "include_bogo_offers": true,
                "deeplink": "zomato://restaurant/7421967",
                "is_table_reservation_supported": 1,
                "has_table_booking": 1,
                "book_url": "https://www.zomato.com/jakarta/3-wise-monkeys-senopati/book?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
                "events_url": "https://www.zomato.com/jakarta/3-wise-monkeys-senopati/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1"
            }
        },
        {
            "restaurant": {
                "R": {
                    "res_id": 18918778
                },
                "apikey": "05d2f9480e0347e4c0e0ea6095c55a14",
                "id": "18918778",
                "name": "Hachi Grill",
                "url": "https://www.zomato.com/jakarta/hachi-grill-gatot-subroto?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
                "location": {
                    "address": "Synthesis Square, Tower 2, Lantai Ground, Jl. Gatot Subroto No. 177 A, Gatot Subroto, Jakarta",
                    "locality": "Gatot Subroto",
                    "city": "Jakarta",
                    "city_id": 74,
                    "latitude": "-6.2405790809",
                    "longitude": "106.8372777477",
                    "zipcode": "",
                    "country_id": 94,
                    "locality_verbose": "Gatot Subroto, Jakarta"
                },
                "switch_to_order_menu": 0,
                "cuisines": "Grill, Japanese",
                "average_cost_for_two": 250000,
                "price_range": 3,
                "currency": "IDR",
                "offers": [],
                "opentable_support": 0,
                "is_zomato_book_res": 0,
                "mezzo_provider": "OTHER",
                "is_book_form_web_view": 0,
                "book_form_web_view_url": "",
                "book_again_url": "",
                "thumb": "",
                "user_rating": {
                    "aggregate_rating": "4.3",
                    "rating_text": "Very Good",
                    "rating_color": "5BA829",
                    "votes": "131",
                    "has_fake_reviews": 0
                },
                "photos_url": "https://www.zomato.com/jakarta/hachi-grill-gatot-subroto/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop",
                "menu_url": "https://www.zomato.com/jakarta/hachi-grill-gatot-subroto/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop",
                "featured_image": "",
                "has_online_delivery": 0,
                "is_delivering_now": 0,
                "has_fake_reviews": 0,
                "include_bogo_offers": true,
                "deeplink": "zomato://restaurant/18918778",
                "is_table_reservation_supported": 0,
                "has_table_booking": 0,
                "events_url": "https://www.zomato.com/jakarta/hachi-grill-gatot-subroto/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1"
            }
        },
        {
            "restaurant": {
                "R": {
                    "res_id": 7426032
                },
                "apikey": "05d2f9480e0347e4c0e0ea6095c55a14",
                "id": "7426032",
                "name": "Shabu Hachi",
                "url": "https://www.zomato.com/jakarta/shabu-hachi-cilandak?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
                "location": {
                    "address": "Jl. Ampera Raya No. 127, Cilandak, Jakarta",
                    "locality": "Cilandak",
                    "city": "Jakarta",
                    "city_id": 74,
                    "latitude": "-6.2804306369",
                    "longitude": "106.8198839575",
                    "zipcode": "",
                    "country_id": 94,
                    "locality_verbose": "Cilandak, Jakarta"
                },
                "switch_to_order_menu": 0,
                "cuisines": "Japanese",
                "average_cost_for_two": 350000,
                "price_range": 3,
                "currency": "IDR",
                "offers": [],
                "opentable_support": 0,
                "is_zomato_book_res": 0,
                "mezzo_provider": "OTHER",
                "is_book_form_web_view": 0,
                "book_form_web_view_url": "",
                "book_again_url": "",
                "thumb": "https://b.zmtcdn.com/data/pictures/2/7426032/3469a73d4a073c2e6ae8fb549a68664f.jpg?fit=around%7C200%3A200&crop=200%3A200%3B%2A%2C%2A",
                "user_rating": {
                    "aggregate_rating": "4.5",
                    "rating_text": "Excellent",
                    "rating_color": "3F7E00",
                    "votes": "1428",
                    "has_fake_reviews": 0
                },
                "photos_url": "https://www.zomato.com/jakarta/shabu-hachi-cilandak/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop",
                "menu_url": "https://www.zomato.com/jakarta/shabu-hachi-cilandak/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop",
                "featured_image": "https://b.zmtcdn.com/data/pictures/2/7426032/3469a73d4a073c2e6ae8fb549a68664f.jpg?output-format=webp",
                "has_online_delivery": 0,
                "is_delivering_now": 0,
                "has_fake_reviews": 0,
                "include_bogo_offers": true,
                "deeplink": "zomato://restaurant/7426032",
                "is_table_reservation_supported": 0,
                "has_table_booking": 0,
                "events_url": "https://www.zomato.com/jakarta/shabu-hachi-cilandak/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1"
            }
        },
        {
            "restaurant": {
                "R": {
                    "res_id": 18567253
                },
                "apikey": "05d2f9480e0347e4c0e0ea6095c55a14",
                "id": "18567253",
                "name": "Sushi Hiro",
                "url": "https://www.zomato.com/jakarta/sushi-hiro-senopati?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
                "location": {
                    "address": "Jl. Suryo No. 24, Senopati, Jakarta",
                    "locality": "Senopati",
                    "city": "Jakarta",
                    "city_id": 74,
                    "latitude": "-6.2353127493",
                    "longitude": "106.8132877350",
                    "zipcode": "",
                    "country_id": 94,
                    "locality_verbose": "Senopati, Jakarta"
                },
                "switch_to_order_menu": 0,
                "cuisines": "Sushi, Japanese",
                "average_cost_for_two": 400000,
                "price_range": 4,
                "currency": "IDR",
                "offers": [],
                "opentable_support": 0,
                "is_zomato_book_res": 0,
                "mezzo_provider": "OTHER",
                "is_book_form_web_view": 0,
                "book_form_web_view_url": "",
                "book_again_url": "",
                "thumb": "https://b.zmtcdn.com/data/pictures/3/18567253/234c8d74022f82e43556504198cbb885.jpg?fit=around%7C200%3A200&crop=200%3A200%3B%2A%2C%2A",
                "user_rating": {
                    "aggregate_rating": "4.9",
                    "rating_text": "Excellent",
                    "rating_color": "3F7E00",
                    "votes": "4378",
                    "has_fake_reviews": 0
                },
                "photos_url": "https://www.zomato.com/jakarta/sushi-hiro-senopati/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop",
                "menu_url": "https://www.zomato.com/jakarta/sushi-hiro-senopati/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop",
                "featured_image": "https://b.zmtcdn.com/data/pictures/3/18567253/234c8d74022f82e43556504198cbb885.jpg?output-format=webp",
                "has_online_delivery": 0,
                "is_delivering_now": 0,
                "has_fake_reviews": 0,
                "include_bogo_offers": true,
                "deeplink": "zomato://restaurant/18567253",
                "is_table_reservation_supported": 0,
                "has_table_booking": 0,
                "events_url": "https://www.zomato.com/jakarta/sushi-hiro-senopati/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1"
            }
        },
        {
            "restaurant": {
                "R": {
                    "res_id": 18875696
                },
                "apikey": "05d2f9480e0347e4c0e0ea6095c55a14",
                "id": "18875696",
                "name": "Kintaro Sushi",
                "url": "https://www.zomato.com/jakarta/kintaro-sushi-1-senopati?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
                "location": {
                    "address": "Jl. Suryo No. 20, Senopati, Jakarta",
                    "locality": "Senopati",
                    "city": "Jakarta",
                    "city_id": 74,
                    "latitude": "-6.2346814926",
                    "longitude": "106.8131626770",
                    "zipcode": "",
                    "country_id": 94,
                    "locality_verbose": "Senopati, Jakarta"
                },
                "switch_to_order_menu": 0,
                "cuisines": "Sushi, Japanese",
                "average_cost_for_two": 200000,
                "price_range": 3,
                "currency": "IDR",
                "offers": [],
                "opentable_support": 0,
                "is_zomato_book_res": 0,
                "mezzo_provider": "OTHER",
                "is_book_form_web_view": 0,
                "book_form_web_view_url": "",
                "book_again_url": "",
                "thumb": "https://b.zmtcdn.com/data/pictures/chains/5/18530405/0feeddcbe877a8e27526a8cf5b501edf.jpg?fit=around%7C200%3A200&crop=200%3A200%3B%2A%2C%2A",
                "user_rating": {
                    "aggregate_rating": "4.8",
                    "rating_text": "Excellent",
                    "rating_color": "3F7E00",
                    "votes": "873",
                    "has_fake_reviews": 0
                },
                "photos_url": "https://www.zomato.com/jakarta/kintaro-sushi-1-senopati/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop",
                "menu_url": "https://www.zomato.com/jakarta/kintaro-sushi-1-senopati/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop",
                "featured_image": "https://b.zmtcdn.com/data/pictures/chains/5/18530405/0feeddcbe877a8e27526a8cf5b501edf.jpg?output-format=webp",
                "has_online_delivery": 0,
                "is_delivering_now": 0,
                "has_fake_reviews": 0,
                "include_bogo_offers": true,
                "deeplink": "zomato://restaurant/18875696",
                "is_table_reservation_supported": 0,
                "has_table_booking": 0,
                "events_url": "https://www.zomato.com/jakarta/kintaro-sushi-1-senopati/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1"
            }
        },
        {
            "restaurant": {
                "R": {
                    "res_id": 18923861
                },
                "apikey": "05d2f9480e0347e4c0e0ea6095c55a14",
                "id": "18923861",
                "name": "Kilo",
                "url": "https://www.zomato.com/jakarta/kilo-senopati?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
                "location": {
                    "address": "Jl. Gunawarman No. 16, Senopati, Jakarta",
                    "locality": "Senopati",
                    "city": "Jakarta",
                    "city_id": 74,
                    "latitude": "-6.2357560000",
                    "longitude": "106.8073630000",
                    "zipcode": "",
                    "country_id": 94,
                    "locality_verbose": "Senopati, Jakarta"
                },
                "switch_to_order_menu": 0,
                "cuisines": "Asian",
                "average_cost_for_two": 400000,
                "price_range": 4,
                "currency": "IDR",
                "offers": [],
                "opentable_support": 0,
                "is_zomato_book_res": 0,
                "mezzo_provider": "OTHER",
                "is_book_form_web_view": 0,
                "book_form_web_view_url": "",
                "book_again_url": "",
                "thumb": "",
                "user_rating": {
                    "aggregate_rating": "4.0",
                    "rating_text": "Very Good",
                    "rating_color": "5BA829",
                    "votes": "160",
                    "has_fake_reviews": 0
                },
                "photos_url": "https://www.zomato.com/jakarta/kilo-senopati/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop",
                "menu_url": "https://www.zomato.com/jakarta/kilo-senopati/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop",
                "featured_image": "",
                "has_online_delivery": 0,
                "is_delivering_now": 0,
                "has_fake_reviews": 0,
                "include_bogo_offers": true,
                "deeplink": "zomato://restaurant/18923861",
                "is_table_reservation_supported": 0,
                "has_table_booking": 0,
                "events_url": "https://www.zomato.com/jakarta/kilo-senopati/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1"
            }
        }
    ]
}

module.exports = data