//All restos
export const FETCH_JAKSEL_RESTOS = 'FETCH_JAKSEL_RESTOS_FROM_ZOMATOS'
export const FETCH_ERROR = 'FETCH_ALL_RESTOS_FROM_ZOMATOS_ERROR'

//Resto Detail
export const RESTO_DETAIL = 'FETCH_RESTO_DETAIL_FROM_ZOMATOS'
export const FETCH_DETAIL_ERROR = 'FETCH_RESTO_FROM_ZOMATOS_ERROR'
export const RESET_DETAIL_LOADING = 'RESET_LOADING_IN_RESTO_DETAIL_TO_TRUE'

//Resto Reviews
export const FETCH_RESTO_REVIEWS = 'GET_RESTO_REVIEWS_FROM_ZOMATOS'
export const FETCH_REVIEWS_ERROR = 'ERROR_FETCHING_RESTO_REVIEWS'
export const RESET_REVIEW_LOADING = 'RESET_LOADING_IN_REVIEW'

//User Setting
export const ISLOGIN = 'SET_IS_LOGIN_IF_USER_JUST_LOGIN'
export const WHOSLOGIN = 'SET_USER_JUST_LOGIN'
export const USERSIGNOUT = 'SET_ISLOGIN_TO_FALSE_AND_REMOVE_DATA_IN_WHOSLOGIN'

//Categories
export const FETCH_CATEGORIES = 'FETCH_ALL_CATEGORIES_FROM_ZOMATO'
export const FETCH_CATEGORIES_ERROR = 'FETCHING_CATEGORIES_ERROR'

//Restaurants By Category
export const FETCH_RESTOS_BY_CAT = 'FETCH_ALL_RESTAURANTS_BY_CATEGORY'
export const FETCH_RESTOS_BY_CAT_ERROR = 'FETCH_RESTOS_BY_CAT_ERROR'

//Fetch Cities
export const FETCH_CITIES = 'FETCH_CITIES_FROM_ZOMATO'
export const FETCH_CITIES_ERROR = 'FETCH_CITIES_ERROR'

//Search
export const SEARCH_RESTOS = 'FETCH_RESTOS_BY_QUERY'

//Restos By Loc
export const RESTOS_BY_LOC = 'FETCH_RESTOS_BY_LOCATION'
export const FETCH_RESTOSBYLOC_ERROR = 'FETCH_RESTOS_BY_LOC_ERROR'
